# name: Your New Jekyll Site
# markdown: redcarpet
# pygments: true
name: PowerToWeb
lsi: false
markdown: redcarpet # rdiscount
pygments: true
permalink: /:title
paginate: 10
category_dir: topics
category_title_prefix: CAT
exclude: ["lib", "blog.rb", "Capfile", "config", "log", "Rakefile", "tmp"]
destination: public

excerpt_separator: "\n\n"

safe:        false